version: "3.9"

services:

  redis-stack:
    image: redis/redis-stack:7.2.0-v4
    container_name: redis-stack
    ports:
      - 6379:6379
      - 8001:8001
    volumes: 
      - redis-stack:/data
      - ./local-redis-stack.conf:/redis-stack.conf
    # networks:
    #   - nobin_local

volumes:
  redis-stack:

# networks:
#   nobin_local:
#     external:
#       true