databases:
  - name: komododb
    plan: free

services:
  # FerretDB service
  - type: pserv # Private Service
    name: ferretdb
    runtime: image
    image:
      url: ghcr.io/ferretdb/ferretdb:2.5.0
    envVars:
      - key: FERRETDB_POSTGRESQL_URL
        fromDatabase:
          name: komododb
          property: connectionString
    disk:
      name: ferretdbstate
      mountPath: /state
      sizeGB: 1

  # Komodo Core service
  - type: web
    name: komodo-core
    plan: free #
    runtime: image
    image:
      url: ghcr.io/moghtech/komodo-core:latest
    envVars:
      - key: KOMODO_DATABASE_ADDRESS
        fromService:
          name: ferretdb
          type: pserv
          property: hostport

      - key: KOMODO_DATABASE_USERNAME
        fromDatabase:
          name: komododb
          property: user

      - key: KOMODO_DATABASE_PASSWORD
        fromDatabase:
          name: komododb
          property: password

      # Adds all environment variables from an environment group
      - fromGroup: komodo
