services:
  beszel:
    image: henrygd/beszel:latest
    networks:
      - beszel-network
      - proxy-network
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./data/beszel/data:/beszel_data
      - ./data/beszel/socket:/beszel_socket
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  beszel-agent:
    image: henrygd/beszel-agent:latest
    volumes:
      - ./data/beszel/socket:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
    network_mode: host
    environment:
      LISTEN: 45876
      # Do not remove quotes around the key
      KEY: 'UPDATE WITH YOUR PUBLIC KEY (copy from "Add system" dialog)'
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]
    networks:
      - beszel-network

networks:
  beszel-network:
    external: true
  proxy-network:
    external: true
