services:
  bugsink:
    image: bugsink/bugsink
    environment:
      - SECRET_KEY=cyNpVa9N8bQAqu4FFc6WumWsYiK+p/ycZMi86IlmZ2dA495IvAkomx8JDKp/q2GH/2E=
      - CREATE_SUPERUSER=admin:admin
      - PORT=8000
    networks:
      - resom-saleor-backend
      - proxy-network
    deploy:
      replicas: 1
      restart_policy:
        condition: any

networks:
  resom-saleor-backend:
    external: true
  proxy-network:
    external: true
