services:
  dozzle:
    image: amir20/dozzle:latest
    environment:
      - DOZZLE_MODE=swarm
      - DOZZLE_AUTH_PROVIDER=simple
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - source: dozzle-users
        target: /data/users.yml
    deploy:
      mode: global
    networks:
      - dozzle-network
      - proxy-network

networks:
  dozzle-network:
    driver: overlay
  proxy-network:
    external: true

secrets:
  dozzle-users:
    external: true

# users:
#     admin:
#         email: admin@barrzen.com
#         name: Nazrul Islam Khan
#         password: "$2a$12$Bo6kSQXxUjkk84lzyjf3fexsSPm7DMxWyon8Drtr0PY/0.MQC2tfS"
#         filter: name=nobin
