services:
  dpanel:
    image: dpanel/dpanel:lite
    container_name: dpanel
    ports:
      - 8807:8080
    environment:
      APP_NAME: dpanel
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/dpanel:/dpanel
    deploy:
      replicas: 1
      mode: replicated
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 60s
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
    networks:
      - dpanel-network

networks:
  dpanel-network:
    external: true
