services:
  fief-server:
    image: ghcr.io/fief-dev/fief:latest
    command: fief run-server
    networks:
      - proxy-networks
      - postgresql-database
      - redis-network
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      SECRET: ${SECRET}
      FIEF_CLIENT_ID: ${FIEF_CLIENT_ID}
      FIEF_CLIENT_SECRET: ${FIEF_CLIENT_SECRET}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      PORT: ${PORT}
      FORWARDED_ALLOW_IPS: ${FORWARDED_ALLOW_IPS}
      FIEF_DOMAIN: ${FIEF_DOMAIN}
      FIEF_MAIN_USER_EMAIL: ${FIEF_MAIN_USER_EMAIL}
      FIEF_MAIN_USER_PASSWORD: ${FIEF_MAIN_USER_PASSWORD}
      EMAIL_PROVIDER: ${EMAIL_PROVIDER}
      EMAIL_PROVIDER_PARAMS: ${EMAIL_PROVIDER_PARAMS}
      DATABASE_TYPE: ${DATABASE_TYPE}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      REDIS_URL: ${REDIS_URL}
      DEFAULT_FROM_EMAIL: ${DEFAULT_FROM_EMAIL}
      DEFAULT_FROM_NAME: ${DEFAULT_FROM_NAME}

  fief-worker:
    image: ghcr.io/fief-dev/fief:latest
    command: fief run-worker -p 1 -t 1
    networks:
      - postgresql-database
      - redis-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      SECRET: ${SECRET}
      FIEF_CLIENT_ID: ${FIEF_CLIENT_ID}
      FIEF_CLIENT_SECRET: ${FIEF_CLIENT_SECRET}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      PORT: ${PORT}
      FORWARDED_ALLOW_IPS: ${FORWARDED_ALLOW_IPS}
      FIEF_DOMAIN: ${FIEF_DOMAIN}
      FIEF_MAIN_USER_EMAIL: ${FIEF_MAIN_USER_EMAIL}
      FIEF_MAIN_USER_PASSWORD: ${FIEF_MAIN_USER_PASSWORD}
      EMAIL_PROVIDER: ${EMAIL_PROVIDER}
      EMAIL_PROVIDER_PARAMS: ${EMAIL_PROVIDER_PARAMS}
      DATABASE_TYPE: ${DATABASE_TYPE}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      REDIS_URL: ${REDIS_URL}
      DEFAULT_FROM_EMAIL: ${DEFAULT_FROM_EMAIL}
      DEFAULT_FROM_NAME: ${DEFAULT_FROM_NAME}

networks:
  postgresql-database:
    external: true

  redis-network:
    external: true

  proxy-networks:
    external: true
