services:
  meilisearch:
    image: getmeili/meilisearch:v1.15.2
    volumes:
      - meili_data:/meili_data
    environment:
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
      MEILI_HTTP_ADDR: ${MEILI_HTTP_ADDR}
      MEILI_HTTPS_URL: ${MEILI_HTTPS_URL}
    deploy:
      replicas: 1
      mode: replicated
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 60s
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
    networks:
      - meili-network

networks:
  meili-network:
    external: true

volumes:
  meili_data:
