services:
  npm-core:
    image: jc21/nginx-proxy-manager:2.13.4
    ports:
      - 80:80
      - 443:443
      - 81:81
    networks:
      - nginx-proxy-db
      - proxy-traffic-network
    environment:
      DB_POSTGRES_HOST: ${POSTGRES_HOST}
      DB_POSTGRES_PORT: ${POSTGRES_PORT}
      DB_POSTGRES_USER: ${POSTGRES_USER}
      DB_POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_POSTGRES_NAME: ${POSTGRES_DB}
    volumes:
      - /container-data/swarm/services/nginx-proxy-manager/data:/data
      - /container-data/swarm/services/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
    healthcheck:
      test: ["CMD", "/usr/bin/check-health"]
      interval: 10s
      timeout: 3s

networks:
  nginx-proxy-db:
    external: true
  proxy-traffic-network:
    external: true
