services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:2.12.3
    ports:
      - 80:80
      - 443:443

    networks:
      - proxy-network
      - nginx-proxy-db
    environment:
      DB_POSTGRES_HOST: ${POSTGRES_HOST}
      DB_POSTGRES_PORT: ${POSTGRES_PORT}
      DB_POSTGRES_USER: ${POSTGRES_USER}
      DB_POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_POSTGRES_NAME: ${POSTGRES_DB}
    volumes:
      - ./data/nginx-proxy-manager/data:/data
      - ./data/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]

  nginx-postgres-db:
    image: cgr.dev/chainguard/postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data/nginx-proxy-manager/postgres-data:/var/lib/postgresql/data
    networks:
      - nginx-proxy-db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]

networks:
  nginx-proxy-db:
    external: true
  proxy-network:
    external: true
