services:
  agent:
    image: portainer/agent:lts
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - portainer-network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]
      labels:
        proxy.exclude: "true"

  portainer:
    image: portainer/portainer-ce:lts
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    volumes:
      - /root/docker_files/container_data/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - portainer-network
      - proxy-network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    ports: # Remove After Domain Setup
      - "9443:9443"

networks:
  proxy-network:
    external: true
  portainer-network:
    external: true
