services:
  postgres:
    image: nobinkhan/postgres:18.1-wolfi
    volumes:
      - /container-data/swarm/database/postgres/nginx-proxy-manager/data:/var/lib/postgresql/data
    networks:
      - postgresql-network
      - nginx-proxy-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  postgresql-network:
    external: true
  nginx-proxy-db:
    external: true
