services:
  postgres:
    image: cgr.dev/chainguard/postgres:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      POSTGRES_DB: post-db
      POSTGRES_USER: post-user
      POSTGRES_PASSWORD: /run/secrets/Postgres-Database-Password
    volumes:
      - /container_data/postgresql:/var/lib/postgresql/data
    networks:
      - postgresql-network
      - proxy-network

  pgadmin:
    image: dpage/pgadmin4:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      PGADMIN_DEFAULT_EMAIL: email.example.com
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/Pgadmin-Admin-Password
    networks:
      - postgresql-network
      - proxy-network
    volumes:
      - /container_data/pgadmin:/var/lib/pgadmin

networks:
  proxy-network:
    external: true
  postgresql-network:
    external: true
