services:
  syncthing:
    image: linuxserver/syncthing:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /root/docker_files/syncthing:/config
      - /root/docker_files:/docker_files
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    networks:
      - syncthing-network
      - proxy-network

networks:
  syncthing-network:
    external: true
  proxy-network:
    external: true
