services:
  valkey:
    image: cgr.dev/chainguard/valkey:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1.5'
          memory: 2048M
      restart_policy:
        condition: on-failure
    networks:
      - redis-network
    volumes:
      - /root/docker_files/redis-valkey/data:/data

networks:
  redis-network:
    external: true
