services:
  valkey:
    image: cgr.dev/chainguard/valkey:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - redis-network
    volumes:
      - redis-valkey-data:/data

volumes:
  redis-valkey-data:

networks:
  redis-network:
    external: true
