services:
  zerofs9p:
    image: ghcr.io/barre/zerofs:0.17.3
    command: ["run", "--config", "/etc/zerofs/zerofs.toml"]
    ports:
      - 5564:5564
    volumes:
      - /var/cache/zerofs:/var/cache/zerofs
      - /etc/zerofs:/etc/zerofs
      - /tmp:/tmp
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.swarm == leader]