services:
  dpanel:
    image: dpanel/dpanel:lite
    container_name: dpanel
    restart: always
    ports:
      - 8807:8080
    environment:
      APP_NAME: dpanel
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./container-volume/dpanel:/dpanel
    networks:
      - dpanel-networks
      - proxy-networks

networks:
  dpanel-networks:
    external: true

  proxy-networks:
    external: true
