# Generated by Django 4.2.8 on 2023-12-12 09:59

import ambulance.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ambulance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ambulanceType",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("minPrice", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("maxPrice", models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Ambulances",
            },
        ),
        migrations.CreateModel(
            name="AmbulanceOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pickupAddress",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "dropAddress",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "contactNumber",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid international mobile phone number starting with +(country code)",
                                regex="^\\+(?:[0-9]●?){6,14}[0-9]$",
                            ),
                        ],
                        verbose_name="Contact Phone Number",
                    ),
                ),
                (
                    "travelTime",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        validators=[ambulance.validators.validate_time],
                    ),
                ),
                ("SpecialNote", models.TextField(blank=True, null=True)),
                ("totalBill", models.PositiveIntegerField(blank=True, null=True)),
                ("cbProfit", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "orderStatus",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pending", "Pending"),
                            ("Canceled", "Canceled"),
                            ("Confirmed", "Confirmed"),
                            ("Completed", "Completed"),
                        ],
                        default="Pending",
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "isPaidToCB",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("isActive", models.BooleanField(blank=True, default=True, null=True)),
                ("created", models.DateTimeField(auto_now=True, null=True)),
                ("updated", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "ambulance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ambulance.ambulance",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "AmbulanceOrders",
            },
        ),
    ]
