version: "3.9"

services:
  pgadmin4:
    image: dpage/pgadmin4:7.5
    container_name: pgadmin4
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin4:/var/lib/pgadmin
    networks:
      - nobin_local

volumes:
  pgadmin4:

networks:
  nobin_local:
    external:
      true