services:
  rabbitmq:
    image: rabbitmq:4.0.5-management-alpine
    hostname: "rabbitmq-{{.Task.Slot}}"
    networks:
      - nginx_ingress
      - rabbitmq-cluster
    configs:
      - source: rabbitmq-config
        target: /etc/rabbitmq/rabbitmq.conf
    environment:
      - RABBITMQ_ERLANG_COOKIE=SECRET_COOKIE
      - RABBITMQ_USE_LONGNAME=true
      - RABBITMQ_CLUSTER_PARTITION_HANDLING=autoheal
    deploy:
      replicas: 3
      restart_policy:
        condition: any
    ports:
      - 5672:5672  # AMQP port for inter-service communication
      - 15672:15672  # Management UI port for external access
      - 25672:25672  # RabbitMQ inter-node communication (internal)

networks:
  rabbitmq-cluster:
    external: true
  nginx_ingress:
    external: true

configs:
  rabbitmq-config:
    external: true