ARG BASE_IMAGE=ghcr.io/saleor/saleor:latest
FROM ${BASE_IMAGE}

COPY mini_server.py ping-loop.sh start_api.sh start_worker.sh start_scheduler.sh /app/

RUN apt-get update && apt-get upgrade -y \
  && apt-get install -y \
  curl \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* \
  && chmod +x /app/ping-loop.sh \
  && chmod +x /app/start_api.sh \
  && chmod +x /app/start_worker.sh \
  && chmod +x /app/start_scheduler.sh

CMD [ "/app/start_api.sh" ]
