services:
  proxy:
    image: image.koompi.org/library/pingora-proxy-server
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./cert-files:/certbot
      - ./acme-files:/var/www/html/.well-known/acme-challenge
    environment:
      - SWARM_MODE=true
      - SWARM_NETWORKS=proxy-networks
      - LOG_LEVEL=info
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
    networks:
      - proxy-networks

networks:
  proxy-networks:
    external: true