version: "3.9"

services:
  inventory:
    image: nayeem0987/pos:latest
    container_name: cb_pos
    ports:
      - 3050:3000
    environment:
      REACT_APP_BASE_URL: ${REACT_APP_BASE_URL}
    #   PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    # volumes:
    #   - pgadmin4:/var/lib/pgadmin
    networks:
      - nobin_local

# volumes:
#   pgadmin4:

networks:
  nobin_local:
    external:
      true