services:
  agent:
    image: portainer/agent:lts
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer-ce:lts
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    volumes:
      - portainer_data:/data
    networks:
      - agent_network
      - traefik-proxy  # Attach Portainer to the Traefik network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.rule=Host(`portainer.resom.com.br`)
      - traefik.http.routers.portainer.entrypoints=https
      - traefik.http.routers.portainer.tls.certresolver=letsencrypt
      - traefik.http.services.portainer.loadbalancer.server.port=9000
      - traefik.http.routers.portainer.service=portainer

networks:
  agent_network:
    driver: overlay
    attachable: true
  traefik-proxy:
    external: true  # Attach to the existing Traefik network

volumes:
  portainer_data:
