version: "3.9"

services:
  meilisearch:
    image: getmeili/meilisearch:v1.5.1
    container_name: meilisearch
    environment:
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
    volumes:
      - meili-search:/data.ms
    ports:
      - "7700:7700"
    # networks:
    #   - nobin_local



volumes:
  meili-search:

# networks:
#   nobin_local:
#     external:
#       true