version: "3.9"

services:

  redis:
    image: redis:7.0.12-alpine3.18
    container_name: redis
    ports:
      - 6379:6379
    volumes: 
      - redis:/data
    networks:
      - nobin_local

volumes:
  redis:

networks:
  nobin_local:
    external:
      true