run-name: Build Container Images by @${{ github.actor }}

on:
  workflow_dispatch:

env:
  GITHUB_IMAGE_REGISTRY: ghcr.io
  GITHUB_IMAGE_NAME: nobinkhan/docker-stack/redis
  REDIS_UPSTREAM_IMAGE_TAG: 7.4.2-alpine3.21

jobs:
  Build:
    name: "Building Image"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - name: "Checkout Code"
        uses: "actions/checkout@v4"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log into github registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GITHUB_IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.GITHUB_IMAGE_REGISTRY }}/${{ env.GITHUB_IMAGE_NAME }}

      - name: Build and push to GitHub Registry
        id: push-to-github
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./dockerfiles/Dockerfile.redis
          push: true
          platforms: linux/amd64, linux/arm64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/redis:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/redis:${{ env.REDIS_UPSTREAM_IMAGE_TAG }}
            ${{ env.GITHUB_IMAGE_REGISTRY }}/${{ env.GITHUB_IMAGE_NAME }}:latest
            ${{ env.GITHUB_IMAGE_REGISTRY }}/${{ env.GITHUB_IMAGE_NAME }}:${{ env.REDIS_UPSTREAM_IMAGE_TAG }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
